# Nom du workflow affiché dans l’onglet Actions du dépôt
name: CI Pipeline Angular

# Déclencheurs du workflow
on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:  # exécution manuelle
  schedule:
    - cron: '0 3 * * *'  # tous les jours à 03h00 UTC

# Variables d’environnement globales
env:
  NODE_VERSION: '20'
  ANGULAR_CLI_VERSION: '17'
  NODE_ENV: 'production'

# Paramètres par défaut
defaults:
  run:
    shell: bash
    working-directory: frontend

# Permissions du token GitHub
permissions:
  contents: read
  packages: write
  issues: write

# Définition des jobs
jobs:
  build-and-test:
    name: Build and Test Angular App
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Étape 3 : Installer Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli@${{ env.ANGULAR_CLI_VERSION }}

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # Étape 5 : Lancer les tests unitaires
      - name: Run unit tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      # Étape 6 : Build de l’application
      - name: Build Angular app
        run: ng build --prod
